services:
  - type: web
    name: snippet-vault-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && cd api && npx nest build
    startCommand: cd api && node dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb://localhost:27017/snippet-vault
      - key: VAULT_API_KEY
        generateValue: true
      - key: PORT
        value: 10000
